// frontend/src/pages/Diagnosis.tsx
import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { BreadcrumbNav } from '@/components/BreadcrumbNav'
import { fetchDiagnosis } from '@/api/diagnosis'
import type { DiagnosisAction, DiagnosisDisplay, DiagnosisRecord } from '@/types/api'

/* ── Sub-components ──────────────────────────────────────── */

function StepNumber({ n }: { n: number }) {
  if (n === 1) {
    return (
      <div className="w-6 h-6 rounded-full bg-primary text-on-primary flex items-center justify-center flex-shrink-0 font-label-caps text-[12px]">
        {n}
      </div>
    )
  }
  return (
    <div className="w-6 h-6 rounded-full bg-primary/20 text-primary flex items-center justify-center flex-shrink-0 font-label-caps text-[12px]">
      {n}
    </div>
  )
}

function parseActionText(value: string | null): DiagnosisAction[] {
  const lines = (value ?? '')
    .split('\n')
    .map((line) => line.replace(/^\d+[.、]\s*/, '').trim())
    .filter(Boolean)

  return lines.map((line) => {
    const [title, ...rest] = line.split(/[：:]/)
    return {
      title: title.trim(),
      description: rest.join('：').trim(),
    }
  })
}

function fallbackDisplay(data: DiagnosisRecord): DiagnosisDisplay {
  const fault = data.fault
  const actions = parseActionText(data.suggested_actions)

  return {
    fault_type: fault.fault_type_cn ?? data.fault_type_cn ?? '未知故障',
    source_label: fault.fault_id.startsWith('AI_') ? 'AI在线诊断' : '历史样本诊断',
    root_cause: data.root_cause ?? '系统已识别通信指标异常，需要结合关键KPI和现场告警继续确认根因。',
    key_symptoms: ['关键通信指标偏离正常基线', '业务质量存在下降风险'],
    suggested_actions: actions.length > 0
      ? actions
      : [{ title: '人工复核', description: '请复核RSRP、SINR、BER/BLER、PRB利用率和吞吐量后确认处理方案。' }],
    affected_scope: data.affected_scope ?? '影响范围需要结合故障基站、定位结果和实时业务指标继续确认。',
    evidence: fault.station_id ? [`关联基站：${fault.station_id}`] : [],
    review_required: data.review_required === 1,
    review_reason: data.review_required === 1
      ? '系统诊断结果标记为需要运维人员复核。'
      : '当前规则判断可按建议流程处理，处理后继续观察关键指标恢复情况。',
  }
}

/* ── Main Page ───────────────────────────────────────────── */

export default function Diagnosis() {
  const { id: faultId } = useParams<{ id: string }>()
  const [data, setData] = useState<DiagnosisRecord | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!faultId) return
    setLoading(true)
    fetchDiagnosis(faultId)
      .then(setData)
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false))
  }, [faultId])

  if (loading) {
    return (
      <div className="max-w-[1200px] mx-auto flex flex-col gap-gutter animate-fade-in">
        <div className="flex items-center justify-center h-[400px] text-on-surface-variant font-body-md">
          <span className="material-symbols-outlined animate-pulse-scale mr-2">progress_activity</span>
          加载诊断数据...
        </div>
      </div>
    )
  }

  if (error || !data) {
    return (
      <div className="max-w-[1200px] mx-auto flex flex-col gap-gutter animate-fade-in">
        <div className="flex items-center justify-center h-[400px] text-error font-body-md">
          <span className="material-symbols-outlined mr-2">error</span>
          {error ?? '未找到诊断数据'}
        </div>
      </div>
    )
  }

  const fault = data.fault
  const display = data.display ?? fallbackDisplay(data)
  const confidence = fault.confidence == null ? null : (fault.confidence <= 1 ? fault.confidence * 100 : fault.confidence)
  const reviewRequired = display.review_required

  return (
    <div className="max-w-[1200px] mx-auto flex flex-col gap-gutter animate-fade-in">
      {/* ── Header row ────────────────────────────────────── */}
      <div className="flex items-center justify-between mb-2">
        <div className="flex flex-col">
          <BreadcrumbNav
            items={[
              { label: '故障日志', path: '/faults' },
              { label: '诊断建议' },
            ]}
          />
          <h1 className="font-headline-md text-headline-md text-on-surface mt-1">诊断建议</h1>
        </div>
        <div className="flex items-center gap-3">
          <button
            className="px-4 py-2 rounded-lg bg-surface border border-outline-variant text-on-surface hover:bg-surface-container-low transition-colors font-body-sm text-body-sm flex items-center gap-2"
          >
            <span className="material-symbols-outlined text-[18px]">download</span>
            导出报告
          </button>
          <button
            className="px-4 py-2 rounded-lg bg-primary text-on-primary hover:bg-primary/90 transition-colors shadow-sm font-body-sm text-body-sm flex items-center gap-2"
          >
            <span className="material-symbols-outlined text-[18px]">done_all</span>
            采纳建议
          </button>
        </div>
      </div>

      {/* ── Top: Fault Info Card ──────────────────────────── */}
      <section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-card-padding flex flex-col gap-4 relative overflow-hidden">
        {/* Red accent bar */}
        <div className="absolute top-0 left-0 w-full h-1 bg-error" />

        {/* Header: icon + title + badges */}
        <div className="flex items-center justify-between border-b border-outline-variant/50 pb-4">
          <div className="flex items-center gap-3">
            <span className="material-symbols-outlined text-error text-[28px]">gpp_bad</span>
            <h3 className="font-headline-md text-headline-md text-on-surface">
              {fault.fault_type_cn ?? '未知故障'}
            </h3>
          </div>
          <div className="flex gap-2">
            <span className="px-2.5 py-1 rounded-full bg-error-container text-on-error-container font-label-caps text-label-caps uppercase border border-error/20 flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-error" />
              {fault.fault_level ?? '未分级'}
            </span>
            <span className="px-2.5 py-1 rounded-full bg-primary-container text-primary font-label-caps text-label-caps border border-primary/20 flex items-center gap-1">
              <span className="material-symbols-outlined text-[14px]">psychology</span>
              {confidence == null ? display.source_label : `模型置信度 ${confidence.toFixed(1)}%`}
            </span>
          </div>
        </div>

        {/* 4-column info grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
          <div className="flex flex-col gap-1">
            <span className="font-label-caps text-label-caps text-on-surface-variant uppercase">故障编号</span>
            <span className="font-data-mono text-data-mono text-on-surface">{fault.fault_id}</span>
          </div>
          <div className="flex flex-col gap-1">
            <span className="font-label-caps text-label-caps text-on-surface-variant uppercase">检测时间</span>
            <span className="font-data-mono text-data-mono text-on-surface">{fault.detected_at ?? '-'}</span>
          </div>
          <div className="flex flex-col gap-1">
            <span className="font-label-caps text-label-caps text-on-surface-variant uppercase">关联基站</span>
            <span className="font-body-sm text-body-sm text-on-surface">{fault.station_id ?? '-'}</span>
          </div>
          <div className="flex flex-col gap-1">
            <span className="font-label-caps text-label-caps text-on-surface-variant uppercase">故障类型</span>
            <span className="font-body-sm text-body-sm text-on-surface">{display.fault_type}</span>
          </div>
        </div>
      </section>

      {/* ── Middle: Bento Grid ────────────────────────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-gutter">
        {/* Root Cause (原因分析) */}
        <section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-card-padding flex flex-col gap-4">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-8 h-8 rounded-lg bg-surface-container-high flex items-center justify-center text-primary">
              <span className="material-symbols-outlined text-[20px]">troubleshoot</span>
            </div>
            <h3 className="font-headline-md text-headline-md text-on-surface">原因分析</h3>
          </div>
          <div className="prose prose-sm max-w-none text-on-surface-variant font-body-md leading-relaxed space-y-4">
            <p>{display.root_cause}</p>
            <div className="bg-surface-container-low p-3 rounded-lg border border-outline-variant/30 flex items-start gap-3 mt-4">
              <span className="material-symbols-outlined text-secondary text-[20px] mt-0.5">info</span>
              <div className="font-body-sm">
                <span className="block font-medium text-on-surface mb-1">关键症状</span>
                <ul className="list-disc pl-4 space-y-1">
                  {display.key_symptoms.map((symptom) => (
                    <li key={symptom}>{symptom}</li>
                  ))}
                </ul>
              </div>
            </div>
            {display.evidence.length > 0 && (
              <div className="bg-surface-container-low p-3 rounded-lg border border-outline-variant/30 flex items-start gap-3">
                <span className="material-symbols-outlined text-secondary text-[20px] mt-0.5">fact_check</span>
                <div className="font-body-sm">
                  <span className="block font-medium text-on-surface mb-1">诊断依据</span>
                  <ul className="list-disc pl-4 space-y-1">
                    {display.evidence.map((item) => (
                      <li key={item}>{item}</li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
        </section>

        {/* Actions (处理建议) */}
        <section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-card-padding flex flex-col gap-4">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-8 h-8 rounded-lg bg-surface-container-high flex items-center justify-center text-primary">
              <span className="material-symbols-outlined text-[20px]">build_circle</span>
            </div>
            <h3 className="font-headline-md text-headline-md text-on-surface">处理建议</h3>
          </div>
          <ol className="flex flex-col gap-3 font-body-md text-on-surface">
            {display.suggested_actions.length > 0 ? (
              display.suggested_actions.map((action, i) => (
                <li key={i} className="flex gap-3 bg-surface-container-low p-3 rounded-lg border border-outline-variant/20">
                  <StepNumber n={i + 1} />
                  <div>
                    <h4 className="font-medium text-on-surface mb-1">{action.title}</h4>
                    <p className="text-on-surface-variant font-body-sm">{action.description}</p>
                  </div>
                </li>
              ))
            ) : (
              <li className="flex gap-3 bg-surface-container-low p-3 rounded-lg border border-outline-variant/20">
                <StepNumber n={1} />
                <div>
                  <h4 className="font-medium text-on-surface mb-1">人工复核</h4>
                  <p className="text-on-surface-variant font-body-sm">请结合现场告警和关键KPI确认故障根因后处理。</p>
                </div>
              </li>
            )}
          </ol>
        </section>
      </div>

      {/* ── Bottom: Impact & Review ───────────────────────── */}
      <section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-card-padding flex flex-col md:flex-row gap-6 items-center justify-between">
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-3">
            <span className="material-symbols-outlined text-secondary text-[20px]">radar</span>
            <h3 className="font-headline-md text-headline-md text-on-surface">影响范围</h3>
          </div>
          <p className="font-body-md text-on-surface-variant leading-relaxed">
            {display.affected_scope}
          </p>
        </div>

        {reviewRequired ? (
          <div className="flex-shrink-0 bg-error-container/40 border border-error/30 rounded-xl p-4 flex flex-col items-center justify-center text-center w-full md:w-auto max-w-[280px] animate-border-flash">
            <span className="material-symbols-outlined text-error text-[32px] mb-2">engineering</span>
            <span className="font-headline-md text-headline-md text-error mb-1 tracking-tight">需人工复核</span>
            <span className="font-body-sm text-on-error-container">{display.review_reason}</span>
          </div>
        ) : (
          <div className="flex-shrink-0 bg-surface-container-low border border-outline-variant rounded-xl p-4 flex flex-col items-center justify-center text-center w-full md:w-auto max-w-[280px]">
            <span className="material-symbols-outlined text-primary text-[32px] mb-2">task_alt</span>
            <span className="font-headline-md text-headline-md text-primary mb-1 tracking-tight">自动诊断完成</span>
            <span className="font-body-sm text-on-surface-variant">{display.review_reason}</span>
          </div>
        )}
      </section>
    </div>
  )
}

// frontend/src/views/Diagnosis.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRoute } from 'vue-router'
import { fetchDiagnosis } from '../api/diagnosis'
import StatusBadge from '../components/StatusBadge.vue'
import type { DiagnosisRecord } from '../types/api'

const route = useRoute()
const faultId = route.params.id as string

const loading = ref(true)
const error = ref<string | null>(null)
const data = ref<DiagnosisRecord | null>(null)

const fault = computed(() => data.value?.fault ?? null)
const diagnosis = computed(() => data.value ?? null)

/* ------------------------------------------------------------------ */
/*  Parse suggested_actions into a list of strings                    */
/* ------------------------------------------------------------------ */
const actionList = computed(() => {
  const raw = diagnosis.value?.suggested_actions
  if (!raw) return []

  // Try JSON array first
  try {
    const parsed = JSON.parse(raw)
    if (Array.isArray(parsed)) return parsed.map((s: unknown) => String(s).trim())
  } catch {
    // not JSON, continue
  }

  // Try newline split (common for numbered / bulleted lists)
  const lines = raw.split(/\n/).map(s => s.trim()).filter(Boolean)
  if (lines.length > 1) {
    return lines.map(l => l.replace(/^[\d]+[\.\)、]\s*/, '').replace(/^[-*]\s*/, '').trim())
  }

  // Try semicolon / Chinese semicolon split
  const parts = raw.split(/[;；]/).map(s => s.trim()).filter(Boolean)
  if (parts.length > 1) return parts

  // Single item
  return [raw.trim()]
})

/* ------------------------------------------------------------------ */
/*  Confidence display helper                                         */
/* ------------------------------------------------------------------ */
const confidencePercent = computed(() => {
  if (fault.value?.confidence == null) return '--'
  return `${(fault.value.confidence * 100).toFixed(1)}%`
})

/* ------------------------------------------------------------------ */
/*  Fault level -> StatusBadge prop                                   */
/* ------------------------------------------------------------------ */
const levelBadgeStatus = computed(() => {
  const level = fault.value?.fault_level
  if (!level) return '离线'
  if (level === '严重' || level === 'severe' || level === '高' || level === 'high') return '严重'
  if (level === '中' || level === 'medium') return '预警'
  if (level === '低' || level === 'low') return '正常'
  return '需复核'
})

const levelDisplay = computed(() => fault.value?.fault_level ?? '--')

/* ------------------------------------------------------------------ */
/*  review_required: number -> boolean (1 = true)                     */
/* ------------------------------------------------------------------ */
const needsReview = computed(() => diagnosis.value?.review_required === 1)

/* ------------------------------------------------------------------ */
/*  Data loading                                                      */
/* ------------------------------------------------------------------ */
async function loadData() {
  loading.value = true
  error.value = null
  try {
    const result = await fetchDiagnosis(faultId)
    data.value = result
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : '加载诊断数据失败'
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadData()
})
</script>

<template>
  <div class="space-y-6">
    <!-- Loading state -->
    <div v-if="loading" class="flex items-center justify-center py-20">
      <div class="flex flex-col items-center gap-3">
        <div class="w-8 h-8 border-2 border-[#4338ca] border-t-transparent rounded-full animate-spin"></div>
        <span class="text-sm text-slate-500">正在加载诊断数据...</span>
      </div>
    </div>

    <!-- Error state -->
    <div v-else-if="error" class="flex items-center justify-center py-20">
      <div class="bg-white rounded-[0.5rem] border border-[#E2E8F0] p-[20px] text-center max-w-md">
        <div class="w-12 h-12 mx-auto mb-4 rounded-full bg-red-50 flex items-center justify-center">
          <svg class="w-6 h-6 text-red-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10" />
            <path d="M12 8 L12 12" />
            <path d="M12 16 L12.01 16" />
          </svg>
        </div>
        <h3 class="text-base font-semibold text-slate-800 mb-2">加载失败</h3>
        <p class="text-sm text-slate-500 mb-4">{{ error }}</p>
        <button
          @click="loadData()"
          class="px-4 py-2 rounded-lg bg-[#4338ca] text-white text-sm font-medium hover:bg-[#3730a3] transition-colors"
        >
          重新加载
        </button>
      </div>
    </div>

    <!-- Data loaded -->
    <template v-else-if="data">
      <!-- Page header -->
      <div>
        <div class="text-[15px] font-semibold text-slate-800">诊断建议</div>
        <div class="text-[13px] text-slate-500 mt-1">故障 ID: {{ faultId }}</div>
      </div>

      <!-- Top: Fault basic info card -->
      <div class="bg-white rounded-[0.5rem] border border-[#E2E8F0] p-[20px]">
        <h3 class="text-[15px] font-semibold text-slate-800 mb-4">故障基本信息</h3>
        <div class="grid grid-cols-3 gap-x-6 gap-y-3">
          <div class="flex items-center gap-2">
            <span class="text-[12px] text-slate-500 w-[72px] shrink-0">故障 ID</span>
            <span class="text-[13px] text-slate-800 font-medium">{{ fault?.fault_id ?? '--' }}</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="text-[12px] text-slate-500 w-[72px] shrink-0">检测时间</span>
            <span class="text-[13px] text-slate-800">{{ fault?.detected_at ?? '--' }}</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="text-[12px] text-slate-500 w-[72px] shrink-0">基站 ID</span>
            <span class="text-[13px] text-slate-800 font-medium">{{ fault?.station_id ?? '--' }}</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="text-[12px] text-slate-500 w-[72px] shrink-0">故障类型</span>
            <span class="text-[13px] text-slate-800 font-medium">{{ fault?.fault_type_cn ?? '--' }}</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="text-[12px] text-slate-500 w-[72px] shrink-0">故障等级</span>
            <StatusBadge :status="levelBadgeStatus" />
            <span class="text-[13px] text-slate-700">{{ levelDisplay }}</span>
          </div>
          <div class="flex items-center gap-2">
            <span class="text-[12px] text-slate-500 w-[72px] shrink-0">置信度</span>
            <span class="text-[13px] text-slate-800 font-medium">{{ confidencePercent }}</span>
          </div>
        </div>
      </div>

      <!-- Card 1: Root cause analysis -->
      <div class="bg-white rounded-[0.5rem] border border-[#E2E8F0] p-[20px]">
        <h3
          class="text-[15px] font-semibold mb-3 px-3 py-2 rounded-md bg-slate-800 text-white"
        >
          原因分析
        </h3>
        <div class="text-[13px] text-slate-700 leading-relaxed bg-slate-50 rounded-md px-4 py-3">
          {{ diagnosis?.root_cause ?? '暂无原因分析数据' }}
        </div>
      </div>

      <!-- Card 2: Suggested actions -->
      <div class="bg-white rounded-[0.5rem] border border-[#E2E8F0] p-[20px]">
        <h3
          class="text-[15px] font-semibold mb-3 px-3 py-2 rounded-md bg-slate-800 text-white"
        >
          处理建议
        </h3>
        <div v-if="actionList.length > 0" class="space-y-2">
          <div
            v-for="(action, index) in actionList"
            :key="index"
            class="flex items-start gap-3 text-[13px] bg-slate-50 rounded-md px-4 py-3"
          >
            <span
              class="shrink-0 w-5 h-5 rounded-full bg-[#4338ca] text-white text-[11px] font-semibold flex items-center justify-center"
            >
              {{ index + 1 }}
            </span>
            <span class="text-slate-700 leading-relaxed">{{ action }}</span>
          </div>
        </div>
        <div v-else class="text-[13px] text-slate-400 bg-slate-50 rounded-md px-4 py-3">
          暂无处理建议数据
        </div>
      </div>

      <!-- Card 3: Affected scope -->
      <div class="bg-white rounded-[0.5rem] border border-[#E2E8F0] p-[20px]">
        <h3
          class="text-[15px] font-semibold mb-3 px-3 py-2 rounded-md bg-slate-800 text-white"
        >
          影响范围
        </h3>
        <div class="text-[13px] text-slate-700 leading-relaxed bg-slate-50 rounded-md px-4 py-3">
          {{ diagnosis?.affected_scope ?? '暂无影响范围数据' }}
        </div>
      </div>

      <!-- Bottom: Review required badge -->
      <div v-if="needsReview" class="bg-white rounded-[0.5rem] border border-[#E2E8F0] p-[20px]">
        <div class="flex items-center gap-3">
          <div class="relative flex items-center justify-center">
            <!-- Pulse animation ring -->
            <span
              class="absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75 animate-ping"
            ></span>
            <span
              class="relative inline-flex items-center rounded-full bg-red-500 px-4 py-2 text-white text-[14px] font-semibold shadow-sm"
            >
              需人工复核
            </span>
          </div>
          <span class="text-[13px] text-slate-600">系统诊断结果标记为需要运维人员复核，请及时确认处理方案。</span>
        </div>
      </div>

      <div v-else class="bg-white rounded-[0.5rem] border border-[#E2E8F0] p-[20px]">
        <div class="flex items-center gap-2">
          <span
            class="inline-flex items-center rounded-full bg-green-100 px-3 py-1 text-green-700 text-[13px] font-medium"
          >
            自动诊断完成
          </span>
          <span class="text-[13px] text-slate-500">该故障诊断结果无需人工复核。</span>
        </div>
      </div>
    </template>

    <!-- Empty state (no data but not loading / error) -->
    <template v-else>
      <div class="flex items-center justify-center py-20">
        <div class="bg-white rounded-[0.5rem] border border-[#E2E8F0] p-[20px] text-center max-w-md">
          <div class="w-12 h-12 mx-auto mb-4 rounded-full bg-slate-50 flex items-center justify-center">
            <svg class="w-6 h-6 text-slate-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="3" y="3" width="18" height="18" rx="2" />
              <path d="M3 9 L21 9" />
            </svg>
          </div>
          <h3 class="text-base font-semibold text-slate-800 mb-2">暂无诊断数据</h3>
          <p class="text-sm text-slate-500 mb-4">该故障尚未生成诊断建议</p>
          <button
            @click="loadData()"
            class="px-4 py-2 rounded-lg bg-[#4338ca] text-white text-sm font-medium hover:bg-[#3730a3] transition-colors"
          >
            重新加载
          </button>
        </div>
      </div>
    </template>
  </div>
</template>
